-- Migration: 016_create_ai_explanations_table
-- Description: Create ai_explanations table for storing detailed AI reasoning explanations
-- Requirements: 11.3, 11.4, 11.5

-- Create ai_explanations table
CREATE TABLE IF NOT EXISTS ai_explanations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  differential_id UUID NOT NULL REFERENCES differentials(id) ON DELETE CASCADE,
  summary TEXT NOT NULL,
  key_symptoms JSONB NOT NULL DEFAULT '[]',
  clinical_decision_rules JSONB NOT NULL DEFAULT '[]',
  relevant_history JSONB NOT NULL DEFAULT '[]',
  confidence_rationale TEXT NOT NULL,
  medical_references JSONB DEFAULT '[]',
  generated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_ai_explanations_differential_id ON ai_explanations(differential_id);
CREATE INDEX IF NOT EXISTS idx_ai_explanations_generated_at ON ai_explanations(generated_at);

-- Add comments for documentation
COMMENT ON TABLE ai_explanations IS 'Stores detailed AI explanations for differential diagnoses including reasoning, symptoms, decision rules, and references';
COMMENT ON COLUMN ai_explanations.id IS 'Unique identifier for the explanation';
COMMENT ON COLUMN ai_explanations.differential_id IS 'Reference to the differential diagnosis being explained';
COMMENT ON COLUMN ai_explanations.summary IS 'High-level summary of the AI reasoning';
COMMENT ON COLUMN ai_explanations.key_symptoms IS 'JSONB array of SymptomAnalysis objects: {symptom, relevance, contribution}';
COMMENT ON COLUMN ai_explanations.clinical_decision_rules IS 'JSONB array of DecisionRule objects: {name, description, applied, result}';
COMMENT ON COLUMN ai_explanations.relevant_history IS 'JSONB array of HistoryFactor objects: {factor, type, impact}';
COMMENT ON COLUMN ai_explanations.confidence_rationale IS 'Explanation of why the AI assigned the confidence score';
COMMENT ON COLUMN ai_explanations.medical_references IS 'JSONB array of MedicalReference objects: {title, authors, journal, year, doi, url, relevance}';
COMMENT ON COLUMN ai_explanations.generated_at IS 'Timestamp when the explanation was generated by the AI';
COMMENT ON COLUMN ai_explanations.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN ai_explanations.updated_at IS 'Timestamp when the record was last updated';

-- Create trigger to update updated_at timestamp
CREATE TRIGGER update_ai_explanations_updated_at
  BEFORE UPDATE ON ai_explanations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
